name: Build, Deploy to DockerHub and Update to deployment repository

on:
  push:
    branches:
      - main

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Send notification to slack that action triggered
        continue-on-error: true
        id: slack-trigger
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "BACKEND PUSH to MAIN STARTED: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "BACKEND PUSH to MAIN STARTED: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Update DB
        id: prod-env
        run: |
          echo -e "DB_URL=${{ secrets.PROD_DB_URL }}" > ./.env
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dumb-backend:${{ github.run_number }}, ${{ secrets.DOCKERHUB_USERNAME }}/dumb-backend:latest

      - name: Trigger deployment on deployment repo
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: IIT-Hackathon
          repo: deployments
          github_token: ${{ secrets.PAT_TOKEN }}
          github_user: reduan2660
          workflow_file_name: prod-backend.yaml
          propagate_failure: false
          trigger_workflow: true
          wait_workflow: true

      - name: Send custom JSON data to Slack workflow
        id: slack-result
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "BACKEND PUSH TO MAIN RESULT: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "BACKEND PUSH TO MAIN RESULT: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
